package dev.sixik.noesisgui.nsgui;

import dev.sixik.noesisgui.nscore.NSDependencyObject;

/**
 * Provides a base class for all Panel elements. Use Panel elements to position and arrange child
 * objects.
 * <p>
 * Panel contains a collection of UIElement objects, which are in the Children property. Adding a
 * UIElement child to a Panel implicitly adds it to the UIElementCollection for the Panel element.
 * <p>
 * Panel elements do not receive mouse events if a Background is not defined. If you need to handle
 * mouse events but do not want a background for your Panel, use Transparent.
 *
 * <h3>XAML Example:</h3>
 * <pre>{@code
 * <Page xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
 *   <StackPanel>
 *     <Button>Button 1</Button>
 *     <Button>Button 2</Button>
 *   </StackPanel>
 * </Page>
 * }</pre>
 *
 * @see <a href="http://msdn.microsoft.com/en-us/library/system.windows.controls.panel.aspx">
 *      Microsoft Documentation: Panel Class</a>
 */
public class NSPanel extends NSFrameworkElement {

    public NSPanel(long ptr) {
        super(ptr);
    }

    /**
     * Gets or sets panel background
     */
    public final NSBrush getBackground() {
        return new NSBrush(nGetBackground(getPtr()));
    }

    /**
     * Gets or sets panel background
     */
    public final void setBackground(final NSBrush brush) {
        nSetBackground(getPtr(), brush.getPtr());
    }

    /**
     * Gets or sets a value that indicates that this Panel is a container for user interface (UI)
     * items that are generated by an ItemsControl.
     */
    public final boolean getIsItemsHost() {
        return nGetIsItemsHost(getPtr());
    }

    /**
     * Gets or sets a value that indicates that this Panel is a container for user interface (UI)
     * items that are generated by an ItemsControl.
     */
    public final void setIsItemsHost(final boolean value) {
        nSetIsItemsHost(getPtr(), value);
    }

    /**
     * Gets or sets a value that represents the order on the z-plane in which an element appears
     */
    public static int getZIndex(final NSDependencyObject element) {
        return nGetZIndex(element.getPtr());
    }

    /**
     * Gets or sets a value that represents the order on the z-plane in which an element appears
     */
    public static void setZIndex(final NSDependencyObject element, final int value) {
        nSetZIndex(element.getPtr(), value);
    }

    /**
     * Gets children collection
     */
    public final NSUIElementCollection getChildren() {
        return new NSUIElementCollection(nGetChildren(getPtr()));
    }

    private static native long nGetBackground(long ptr);

    private static native void nSetBackground(long ptr, long brush_ptr);

    private static native boolean nGetIsItemsHost(long ptr);

    private static native void nSetIsItemsHost(long ptr, boolean value);

    private static native int nGetZIndex(long element_ptr);

    private static native void nSetZIndex(long element_ptr, int value);

    private static native long nGetChildren(long ptr);
}
